# Maven build container 

FROM maven:3.8.1-openjdk-16 AS maven_build

COPY pom.xml /tmp/

COPY src /tmp/src/

WORKDIR /tmp/

RUN mvn package

# pull base image

FROM openjdk:16-jdk-alpine

COPY --from=maven_build /tmp/target/*.jar app.jar

ENTRYPOINT ["java","-jar","/app.jar"]